exploration_manager:
  drone_num: 1
  auto_start: false
  hybrid_search_radius: 15.0
  unknown_penalty_factor: 2.0

  # Local planner refinement
  refined_num: 7
  refined_radius: 5.0
  max_decay: 0.8
  top_view_num: 15

  fsm:
    odom_world_topic: "/uav_simulator/odometry"
    replan_thresh1: 0.1
    replan_thresh2: 0.2
    replan_thresh3: 3.0
    # replan duration is dynamically adjusted based on the current computation time
    replan_duration_fast: 0.05
    replan_duration_default: 0.1
    replan_duration_slow: 0.2
    #swarm
    attempt_interval: 0.5
    pair_opt_interval: 2.0
    repeat_send_num: 10

    # target poses
    target_poses:
      - x: 10.0
        y: 5.0
        z: 1.0
      - x: -10.0
        y: 5.0
        z: 1.0
